config/routes.rb
Rails.application.routes.draw do
  resources :cards, only: [:index]
  resources :organizations, only: [] do
    get :import, on: :collection
  end

  root 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  # validations
  validates :name, presence: true
  validates :pipefy_id, presence: true, uniqueness: true
  
  # associations
  belongs_to :phase

  alias_attribute :name, :title
end

app/models/organization.rb
class Organization < ApplicationRecord
  # validations
  validates :name, presence: true
  validates :pipefy_id, presence: true, uniqueness: true

  # associations
  has_many :pipes, dependent: :destroy
end

app/models/phase.rb
class Phase < ApplicationRecord
  # validations
  validates :name, presence: true
  validates :pipefy_id, presence: true, uniqueness: true
  
  # associations
  belongs_to :pipe
  has_many :cards, dependent: :destroy

  def field_names
    self.pipe.start_form_fields.map { |f| f['label'] } + self.fields.map { |f| f['label']  }
  end
end

app/models/pipe.rb
class Pipe < ApplicationRecord
  # validations
  validates :name, presence: true
  validates :pipefy_id, presence: true, uniqueness: true

  # associations
  belongs_to :organization
  has_many :phases, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @organizations = Organization.includes(pipes: [phases: :cards])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def import
    if Pipefy::SyncOrganizationGraph.new(organization_id: 92858, pipe_id: 335557).perform
      flash[:notice] = 'Organization imported successfully!'
    else
      flash[:error] = 'Organization was not imported due to an error.'
    end
    
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
  def field_value(card, field)
    card.fields.find { |f| f['name'] == field }.try(:[], 'value')
  end
end

app/views/cards/_card.html.erb
<tr>
  <td><%= card.title %></td>
  <td><%= card.created_on_pipefy_at %></td>
  <td><%= card.due_at %></td>
  <% card.phase.field_names.each do |field| %>
    <td><%= field_value(card, field) %></td>
  <% end %>
</tr>

app/views/cards/index.html.erb
<div>
  <%= button_to 'Fetch new data', import_organizations_path, method: :get, class: 'btn btn-dark float-right' %>

  <% if @organizations.any? %>
    <%= render partial: 'organizations/organization', collection: @organizations %>
  <% else %>
    <p>Click on Fetch new data to get organization cards</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PipefyCards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <p class="alert alert-success" role="alert"><%= flash[:notice] %></p>
      <% elsif flash[:error] %>
        <p class="alert alert-danger" role="alert"><%= flash[:error] %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/_organization.html.erb
<h1 class='title'><%= organization.name %></h1>
<br />
<%= render partial: 'pipes/pipe', collection: organization.pipes %>

app/views/phases/_phase.html.erb
<div class="card">
  <div class="card-header">
    <span>Phase: <strong><%= phase.name %></strong></span>
  </div>
  <div class="card-body">
    <table class="table table-hover cards-table">
      <thead class='thead-dark'>
        <tr>
          <th>Title</th>
          <th>Created at</th>
          <th>Due Date</th>
          <% phase.field_names.each do |field| %>
            <th scope="col"><%= field %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: 'cards/card', collection: phase.cards) || content_tag(:tr, content_tag(:td, 'No cards to display', colspan: phase.field_names.length + 3)) %>
        <!-- empty colspan = custom fields plus title/created at/due date fields -->
      </tbody>
    </table>
  </div>
</div>

app/views/pipes/_pipe.html.erb
<h4 class='sub-title'><%= pipe.name %></h4>

<%= render(partial: 'phases/phase', collection: pipe.phases) || 'No phases to display' %>